#pragma once

#include "bx/engine/core/macros.hpp"

#define ENGINE_VERSION_MAJOR 0
#define ENGINE_VERSION_MINOR 0
#define ENGINE_VERSION_DEV 1

#define ENGINE_VERSION_STR \
ENGINE_XSTR(ENGINE_VERSION_MAJOR) "." \
ENGINE_XSTR(ENGINE_VERSION_MINOR) "." \
ENGINE_XSTR(ENGINE_VERSION_DEV)